### PR TITLE
Fix for issues reported with Simple theme in #149

### PR DESCRIPTION
**Pull request by devansh08**
This should fix the issues with Repo URL trailing space. Also enabled Issues with my simple repo.

Thanks!

### CODE REVIEW

**Comment by devansh08** [comment]
@scorphus Soo I see a failure in the pipeline in this PR, but the error seems to be something abt a rate limit failure ? Am I missing anything in this fix ?

**Comment by scorphus** [comment]
Hey, @devansh08! 👋 

That requires a token that's only available in the repo's context, not in a PR one.

I've changed the workflows and it should work now. Could you please rebase your commits on top of current `master` and force-push them? Thanks!

**Review by scorphus — APPROVED** [review]
Thanks, @devansh08

**Comment by devansh08** [comment]
Thanks!

**Pull request merged**
