### PR TITLE
fix a package after the maitiner changed their username

### PR DESCRIPTION
**Pull request by TruncatedDinosour**
fix a package after the maitiner changed their username

### CODE REVIEW

**Comment by faho** [comment]
This should probably be merged?

**Comment by scorphus** [comment]
That's one of many problems with `packages-main`. This whouldn't exist to start with. Now it's only but a burden.

**Comment by faho** [comment]
Okay, so... should it be removed, then?

**Comment by scorphus** [comment]
We can't just remove it. We can only hope oh-my-fish/oh-my-fish#824 renders it — in some sense — unnecessary.

**Comment by faho** [comment]
But until that's merged, could you at least make the packages here not broken?

As I understand it, this package is currently uninstallable. Others are archived and don't work anymore. Could at least that be changed, in some form of minimal maintenance mode?

And, in the interest of honesty, PRs that add new things should then be closed and it should be communicated that nothing more is happening here.

Of course that means that users don't get a convenient list of things to install and instead have to go looking themselves, but oh well.

**Comment by scorphus** [comment]
Even though this PR is going to be merged, the package it regards is actually currently perfectly installable:

image

One day I — or any other maintainer — will have time — out of their free/spare time — to go over those pending PRs. 

Sure that's somehow convenient for users. But I guess you would agree that a huge list of packages is not only unhelpful but very much useless. My point is that `packages-main` is not the solution for the issue. Maybe an `awesome-oh-my-fish`? But who has time for such thing? We all (?) have family and a life to live.

**Review by scorphus — APPROVED** [review]

**Comment by scorphus** [comment]
Thanks, @TruncatedDinosour.

**Pull request merged**
