### PR TITLE
Update artisan

### PR DESCRIPTION
**Pull request by james2doyle**
The original plugin (https://github.com/thecotne/omf-plugin-artisan) has been archived. Also, the original was actually broken on the current version of fish shell. I forked the original and brought it back to life and added some flag completions

### CODE REVIEW

**Comment by bobthecow** [comment]
You shouldn't need the `init.fish` anymore, as `completions` and `functions` are automatically loaded (and re-loaded when they change). Manually sourcing them actually makes things _worse_ :) 

@thecotne I'm assuming since you archived the original, you wouldn't have any concerns with this fork taking the torch and running with it?

**Comment by thecotne** [comment]
@bobthecow i don't have any objections

**Comment by james2doyle** [comment]
Thanks! Should I tweak this to remove the init?

**Comment by bobthecow** [comment]
>Thanks! Should I tweak this to remove the init?

Yeah, but that shouldn't block merging the package def.

**Pull request merged**
