### PR TITLE
Pipenv plugin: Enables pipenv shell activation

### PR DESCRIPTION
**Pull request by pantuza**
The [pipenv](https://github.com/kennethreitz/pipenv/) author wrote a plugin for automatically activate pipenv shell. I just ported his code to use with Oh My Fish.

> PS: PR title and description were edited to best fit the plugin purpose.

### CODE REVIEW

**Comment by oranja** [comment]
Completions are always encouraged to move upstream to `fish` itself.
I hazard a guess that this won't even be the first program that provides dynamic completions to `fish`. (something in the lines of `eval (program --complete)` )

As a side note, just from skimming the sources: It looks like the completions are only loaded once at install time, in such way that any future `fish` instances will *not* have these completions available.

Anyway, it looks like this plugin also offers automatic `pipenv` shell activation. This is something that you didn't mention at all and does offer helpful functionality to `pipenv` + `omf` users.
My humble suggestion, if I'm correct in what I think I see, is to split the completions and the automatic `pipenv` shell into two PRs:
1. Work with https://github.com/fish-shell/fish-shell to provide the `pipenv` completions straight out of the box.
2. Advertise your `omf-pipenv` plugin as a plugin that activates a `pipenv` shell automatically when entering a `pipenv`-managed directory.

**Comment by pantuza** [comment]
Hi @oranja 

Thank you for reviewing the PR. 

I totally agree with the missing information about the plugin. It really does the shell activation for a directory that has a pipenv environment. 

I have updated the plugin. ```init.fish``` file stays equal. The ```hooks/install.fish``` do not eval the completion anymore. It only runs the ```init.fish``` file to have the plugin loaded at the current fish session. When I open new sessions the plugin works normally too. 

I am thinking about edit this PR with new title and description focusing on the automatic pipenv shell activation. What do you think about it?  

Regards.

**Comment by oranja** [comment]
Definitely, go ahead and edit the PR to reflect the true purpose of the plugin.
The "on fish through omf" part is unnecessary, btw.

It would be nice just to leave a hint that the PR description has been edited. Otherwise our conversation will not make much sense to anyone else.

**Comment by faho** [comment]
The description hasn't been updated, this is quite stale. I'd close it.

**Comment by scorphus** [comment]
Let's try and hear from @pantuza.

**Comment by pantuza** [comment]
Thank you folks for raising this conversation.
Since Pipenv itself is [deprecated](https://medium.com/telnyx-engineering/rip-pipenv-tried-too-hard-do-what-you-need-with-pip-tools-d500edc161d4) and no longer maintained I definitely agree to close this Pull Request.

**Pull request closed without merging**
