### PR TITLE
Add brew-completions plugin

### PR DESCRIPTION
**Pull request by laughedelic**
I just published a plugin with improved Homebrew completions for Fish: https://github.com/laughedelic/brew-completions

### CODE REVIEW

**Comment by laughedelic** [comment]
🆙

**Comment by oranja** [comment]
Hi @laughedelic,
Sorry for the delay.

The policy in this official OMF plugin repository is not to include completion plugins, for the simple reason that many more `fish` users can benefit from your work if you propose these completions in a PR to https://github.com/fish-shell/fish-shell` instead.

If for some reason you can't seem to work with them to include your updated completions, you may come back and we will reconsider adding them as an official OMF plugin.

Hope that this sounds reasonable.

**Comment by laughedelic** [comment]
Thanks for reply. Perfectly makes sense 👍  Could you add a contribution guideline mentioning it? Or At least mention it in the readme.

I didn't submit it to the core fish-shell repo, because I was adviced not to: https://github.com/fish-shell/fish-shell/issues/4271#issuecomment-320505492. I didn't attempt **yet** to submit it to the core Homebrew repo, because I want to keep it independent for a while to avoid long release cycles.  So I thought that having it in the OMF repo would make sense in the current state. But I unsestand your position on it.

**Comment by oranja** [comment]
Perhaps one of the core members will agree to include this plugin for a limited period of time if you submit the completions upstream and it takes time, or you know in advance that it will take some time.

**Comment by bobthecow** [comment]
While the final destination is being sorted out, the completions can be installed via URL, too?

**Comment by laughedelic** [comment]
@bobthecow You mean `omf install https://github.com/laughedelic/brew-completions`? Yes, there's no problem with it.

**Comment by bobthecow** [comment]
Yep, that's the one.

**Pull request closed without merging**
