### PR TITLE
Add ghcup plugin

### PR DESCRIPTION
**Pull request by develop7**
Introduces an [ghcup](https://www.haskell.org/ghcup/) (a Haskell toolchain manager) integration plugin.

### CODE REVIEW

**Comment by derekstavis** [comment]
For completions-only packages, we generally recommend trying to get them accepted into github.com/fish-shell/fish-shell, so they work for everyone by default. In general, fish-shell is pretty receptive :)

Wanna give that a shot? If not, we're happy to have them here.

**Comment by develop7** [comment]
@derekstavis not sure why do you think this package is completions-only, to me it's quite the opposite: the https://github.com/develop7/omf-ghcup/blob/master/completions/ghcup.fish is a mere stub generated by `omf init`. https://github.com/develop7/omf-ghcup/blob/master/init.fish, on the other hand, is a rip-off of [`plugin-rustup`'s one](https://github.com/oh-my-fish/plugin-rustup/blob/master/init.fish).

**Comment by derekstavis** [comment]
Sorry that's my misunderstanding then. If it's not completions only I'm fine with it. Sorry about my confusion.

**Comment by develop7** [comment]
Woo, thanks!

**Pull request merged**
